import './globals.css'
import './satoshi.css'
import { lazy } from 'react'
import Theme from '@/context/theme/ThemeProvider'

import { Inter } from 'next/font/google'
import { ToastContainer } from 'react-toastify'
const inter = Inter({ subsets: ['latin'] })
const DefaultLayout = lazy(() => import('./layout/DefaultLayout'))

export const metadata = {
  title: 'Dashboard | Admin Panel',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Theme>
          <DefaultLayout>
            <ToastContainer
              position='top-right'
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme='light dark:dark'
            />
            {children}
          </DefaultLayout>
        </Theme>
      </body>
    </html>
  )
}
